version: "3.8"
services:
  web-app:
    build: .
    ports:
      - target: 80
        published: 80
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /src
  redis:
    image: "redis:alpine"
    networks:
      counter-net:

networks:
  counter-net:

volumes:
  counter-vol:
