[tool.poetry]
name = "DockerDive"
version = "0.1.0"
description = ""
authors = ["NaveenKumarReddy8 <mr.naveen8@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.63.0"
uvicorn = {extras = ["standard"], version = "^0.13.4"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.9.1"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
